<h1 style="text-align:center;">Practical 7</h1>

In [ ]:
import pandas as pd
import numpy as np
import random

**1) to create a dataframe from a dictionary and display it**

In [ ]:
data_frame2 = {"first Number": np.random.randint(1,50,4), "Second Number": np.random.randint(1,50,4)}

data_frame2 = pd.DataFrame(data_frame2, index=["a", "b", "c", "d"])
print("Data Frame :\n", data_frame2,sep="")

**2) to sort the DataFrame first by 'name' in ascending order**

In [ ]:
data_frame3 = {"Name":["harsh","harshal","arya","vansh","nayan"],"Enrollment":[31, 46, 64, 37, 36]}
data_frame3 = pd.DataFrame(data_frame3)
print("Data Frame : \n",data_frame3,sep="")
data_frame3 = data_frame3.sort_values(by="Name",ascending=True)
print("\nData Frame : \n",data_frame3,sep="")

**3) to delete the one specific column from the DataFrame**

In [ ]:
data_frame4 = pd.DataFrame({"Name":["harsh","harshal","arya","vansh","nayan"],"Enrollment":[31, 46, 64, 37, 36]})
print("Data Frame :\n",data_frame4,sep="")
data_frame4 = data_frame4.drop(["Enrollment"],axis=1)
print("Data Frame with Deleted column :\n",data_frame4,sep="")

**4) to write a DataFrame to CSV file using tab separator**

In [ ]:
data_frame5 = pd.DataFrame({"Name":["harsh","harshal","arya","vansh","nayan"],"Enrollment":[31, 46, 64, 37, 36]})

print("Data Frame :\n",data_frame5,sep="")
 
data_frame5.to_csv("Students.csv", sep ="\t",index=False)
 
data_frame5 = pd.read_csv("Students.csv",sep="\t")
 
print("\nData from Students.csv :\n",data_frame5,sep="")